//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitimOZ
    {
        public int Id { get; set; }
        public string Aralik { get; set; }
        public string Alan { get; set; }
        public string Okul { get; set; }
        public string Aciklama { get; set; }
    }
}
