//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeri
    {
        public int Id { get; set; }
        public string ResimYol1 { get; set; }
        public string ResimYol2 { get; set; }
        public string ResimYol3 { get; set; }
        public string ResimYol4 { get; set; }
        public string ResimYol5 { get; set; }
    }
}
