//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciBilgi
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> Dtarih { get; set; }
        public string Adress { get; set; }
        public Nullable<int> ZipKod { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Profil { get; set; }
        public string Kaciklama { get; set; }
    }
}
