//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int Id { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage ="Bu Alan Bos Gecilemez")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karekter Girebilirsiniz!")]
        public string Username { get; set; }
        [DisplayName("PassWord")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu Alan Bos Gecilemez")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karekter Girebilirsiniz!")]
        public string Pass { get; set; }
        public string error { get; set; }
    }
}
