//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kisiselwebEntities : DbContext
    {
        public kisiselwebEntities()
            : base("name=kisiselwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeceriOZ> BeceriOZs { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<DeneyimOZ> DeneyimOZs { get; set; }
        public virtual DbSet<EgitimOZ> EgitimOZs { get; set; }
        public virtual DbSet<Iletisim> Iletisims { get; set; }
        public virtual DbSet<OdullOZ> OdullOZs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Servi> Servis { get; set; }
        public virtual DbSet<Galeri> Galeris { get; set; }
        public virtual DbSet<SosyalHesap> SosyalHesaps { get; set; }
        public virtual DbSet<KullaniciBilgi> KullaniciBilgis { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
