//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kisiselWeb22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdullOZ
    {
        public int Id { get; set; }
        public string Yil { get; set; }
        public string IlkKacinci { get; set; }
        public string FirmaAdi { get; set; }
        public string Aciklama { get; set; }
    }
}
